### PR TITLE
Fix #32 Added fullscreen option

### LINKED ISSUE #32: Add feature to run full screen
To run --fullscreen at the end of the command to run the VM in full screen mode.

### PR DESCRIPTION
**Pull request by digitalight**
Have added a --fullscreen flag so VM can be run in full screen if so desired.
If fullscreen is applied, monitor x and y resolution are determined in order to resolve mouse syncing issue.

### CODE REVIEW

**Comment by AnErrupTion** [comment]
With the GTK UI, you can already put full screen (there is already an option), but yeah that's useful.

**Comment by daPhipz** [comment]
I'm on Manjaro KDE, so I don't have that GUI option.
Your PR works very good, I've merged into my fork. You event don't have to set the `--fullscreen` flag when issuing the command, a simple `Ctl + Alt + F` does the trick of entering and exiting fullscren mode.

Thanks for that!

**Comment by digitalight** [comment]
@daPhipz I found doing just Ctrl + Alt + f, the mouse would still be bound to the size of the window so mouse movement was misaligned when in full screen. Hence when you invoke the flag it calculates the full resolution of the screen to resolve this issue and my main reason for the PR.

**Comment by SneWs** [comment]
I would highly recommend getting this into mainline as it's quite useful when running i3 and the likes for example.

**Comment by flexiondotorg** [comment]
Please rebase this PR so it can be merged :smiley:

**Comment by digitalight** [comment]
Hi, I'm not sure what is being ask of me to do. I've not done PR requests like this before. Can you please help explain.

**Comment by digitalight** [comment]
Following a guide on what rebase is about. I think I've done it.
Please let me know if I've done something wrong. I'm learning :smile:

**Comment by digitalight** [comment]
@flexiondotorg Are you waiting for me to do anything more to get this committed? :smile:

**Comment by evereux** [comment]
thank you @digitalight, this is very helpful.

@daPhipz 
> a simple `Ctl + Alt + F` does the trick of entering and exiting fullscren mode.

and thank you for that. 👍

**Comment by daPhipz** [comment]
@evereux Be aware:

> I found doing just Ctrl + Alt + f, the mouse would still be bound to the size of the window so mouse movement was misaligned when in full screen.

**Comment by evereux** [comment]
> @evereux Be aware:
> 
> > I found doing just Ctrl + Alt + f, the mouse would still be bound to the size of the window so mouse movement was misaligned when in full screen.
> > The `--fullscreen` flag prevents that.

I've already seen this behavior when manually changing the size of my Windows 10 guest window so kind of expect this. Cheers.

**Comment by flexiondotorg** [comment]
Thanks for working on this :+1:

**Pull request merged**
