### PR TITLE
Re-enable networking during Windows installation

### LINKED ISSUE #150: Windows 11 Network during installation
I think the problem might not be related to quickemu itself. 
After the installation of Windows 11, I boot it up and go through the initial setup and it asks for a network connection to complete the setup. I think, at that point the network drivers for virtio-net for windows guest is not yet installed and I cannot proceed further. Can anyone suggest any solutions?

```
quickemu --vm windows-11.conf
Quickemu 2.2.6 using /usr/bin/qemu-system-x86_64 v6.1.0
 - Host:     "Garuda Linux" running Linux 5.14 (Gotham)
 - Guest:    Starting windows-11.conf as windows-11
 - CPU:      Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
 - CPU VM:   1 Socket(s), 4 Core(s), 2 Thread(s), 8G RAM
 - BOOT:     EFI (windows)
 - Disk:     windows-11/disk.qcow2 (64G)
 - CD-ROM:   windows-11/virtio-win.iso
 - TPM:      windows-11/windows-11.swtpm-sock (20774)
 - Display:  SDL, qxl-vga, GL (on), VirGL (off)
 - ssh:      On host:  ssh user@localhost -p 22220
 - SPICE:    On host:  spicy --title "windows-11" --port 5930 --spice-shared-dir /home/sixface/Public
 - WebDAV:   On guest: dav://localhost:9843/
```

Command line:
```
/usr/bin/qemu-system-x86_64 -name windows-11,process=windows-11 -pidfile windows-11/windows-11.pid -enable-kvm -machine q35,vmport=off -no-hpet -global kvm-pit.lost_tick_policy=discard -cpu host,kvm=on,+hypervisor,+invtsc,l3-cache=on,migratable=no,hv_frequencies,kvm_pv_unhalt,hv_reenlightenment,hv_relaxed,hv_spinlocks=8191,hv_stimer,hv_synic,hv_time,hv_vapic,hv_vendor_id=1234567890ab,hv_vpindex -smp cores=4,threads=2,sockets=1 -m 8G -device virtio-balloon -smbios type=2,manufacturer=Wimpys World,product=Quickemu,version=2.2.6,serial=jvzclfjbeyq.pbz,location=wimpysworld.com,asset=windows-11 -device qxl-vga,vgamem_mb=128 -display sdl,gl=on -device usb-ehci,id=input -device usb-kbd,bus=input.0 -device usb-tablet,bus=input.0 -audiodev pa,id=audio0,out.mixing-engine=off,out.stream-name=quickemu-windows-11,in.stream-name=quickemu-windows-11 -device intel-hda -device hda-duplex,audiodev=audio0 -rtc base=localtime,clock=host,driftfix=slew -spice disable-ticketing=on,port=5930 -device virtio-serial-pci -chardev spicevmc,id=vdagent0,name=vdagent -device virtserialport,chardev=vdagent0,name=com.redhat.spice.0 -device virtio-rng-pci,rng=rng0 -object rng-random,id=rng0,filename=/dev/urandom -monitor none -serial mon:stdio -device virtio-net,netdev=nic -netdev user,hostname=windows-11,hostfwd=tcp::22220-:22,id=nic -drive if=pflash,format=raw,file=/usr/share/OVMF/x64/OVMF_CODE.fd,readonly=on -drive if=pflash,format=raw,file=windows-11/OVMF_VARS.fd -drive media=cdrom,index=1,file=windows-11/virtio-win.iso -device virtio-blk-pci,drive=SystemDisk -drive id=SystemDisk,if=none,format=qcow2,file=windows-11/disk.qcow2 -device qemu-xhci,id=spicepass -chardev spicevmc,id=usbredirchardev1,name=usbredir -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1 -chardev spicevmc,id=usbredirchardev2,name=usbredir -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2 -chardev spicevmc,id=usbredirchardev3,name=usbredir -device usb-redir,chardev=usbredirchardev3,id=usbredirdev3 -device usb-ccid -chardev spicevmc,id=ccid,name=smartcard -device ccid-card-passthru,chardev=ccid -device virtio-serial-pci -chardev spiceport,id=webdav0,name=org.spice-space.webdav.0 -device virtserialport,chardev=webdav0,name=org.spice-space.webdav.0 -chardev socket,id=chrtpm,path=windows-11/windows-11.swtpm-sock -tpmdev emulator,id=tpm0,chardev=chrtpm -device tpm-tis,tpmdev=tpm0
```

### PR DESCRIPTION
**Pull request by diddledani**
* Force Windows VMs to use AHCI for the cdrom and hard disk devices.
* Re-enable networking during Windows installation.

Fixes #150

### CODE REVIEW

**Comment by flexiondotorg** [comment]
With the network enabled, is it still possible to create local-only accounts?

The network was deliberately disabled during install so the user can still create local accounts, rather than being forced to create/use a network account.

See https://github.com/wimpysworld/quickemu/issues/115

**Comment by diddledani** [comment]
Yes, that's what this PR is fixing

**Comment by diddledani** [comment]
Specifically, the virtio-based hard disk and cdrom devices were causing the Windows setup to trigger business domain only mode. Switching those to AHCI means we can re-enable the network for a better out of the box experience.

**Comment by flexiondotorg** [comment]
Thank you!

**Pull request merged**
