### PR TITLE
Document ram and cpu_count configurations

### PR DESCRIPTION
**Pull request by evereux**

### CODE REVIEW

**Comment by evereux** [comment]
I see the there is already a spice port commit. I'll see if i can figure out how to remove my submit ...

**Comment by flexiondotorg** [comment]
Please rebase this PR so it can be merged :smiley:

**Comment by evereux** [comment]
I think that's now done. git still confuses me. :thinking:

**Comment by flexiondotorg** [comment]
Please can you re-submit this as discrete pull requests that address each of the features you'd like to add.  There is a lot more going on in the PR than documenting some configuration :slightly_smiling_face:

**Pull request closed without merging**
